<?php

namespace Svt\BassemBundle\Repository;

/**
 * ListeCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
