#svt_bassem_admin_section:
#    resource: "@SvtBassemBundle/Resources/config/routing/section.yml"
 #   prefix:   /admin_section

svt_bassem_homepage:
    path:     /
    defaults: { _controller: SvtBassemBundle:Admin:index }

svt_bassem_classe:
    path:    /classes/{id}
    defaults: { _controller: SvtBassemBundle:Admin:classe }
    requirements:
        id: \d

svt_bassem_classeSpec:
    path:    /classe/{classeName}/{id}/{sectionName}/{idSection}
    defaults: { _controller: SvtBassemBundle:Admin:classeSpec }
    requirements:
        id: \d
        idSection: \d

svt_bassem_cours:
    path:    /classe/{classeName}/{id}/{sectionName}/{idSection}/{moduleeName}/{moduleId}
    defaults: { _controller: SvtBassemBundle:Admin:cours }
    requirements:
        id: \d
        idSection: \d
        categoryId: \d


svt_bassem_viewCourse:
    path:    /cours/{id}/{idSection}/{coursId}/{moduleId}
    defaults: { _controller: SvtBassemBundle:Admin:viewCours }
    requirements:
        id: \d
        idSection: \d
        categoryId: \d
        coursId: \d

svt_bassem_contact:
    path:    /contact
    defaults: { _controller: SvtBassemBundle:Admin:contact }

svt_bassem_contact_trait:
    path:    /contact_trait
    defaults: { _controller: SvtBassemBundle:Admin:contactTrait }

